"""link merge requests to many work items

Revision ID: 0f4cfaea3b36
Revises: 7338db7f9191
Create Date: 2026-09-25 12:21:24.089251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0f4cfaea3b36'
down_revision: Union[str, None] = '7338db7f9191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Existing links were derived by matching MR and issue *numbers*, which was wrong, so they are
    # deliberately not copied; the next sync rebuilds them from real GitLab references.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merge_request_work_items',
    sa.Column('merge_request_id', sa.UUID(), nullable=False),
    sa.Column('work_item_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['merge_request_id'], ['merge_requests.id'], ),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ),
    sa.PrimaryKeyConstraint('merge_request_id', 'work_item_id')
    )
    op.drop_constraint('merge_requests_work_item_id_fkey', 'merge_requests', type_='foreignkey')
    op.drop_column('merge_requests', 'work_item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merge_requests', sa.Column('work_item_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('merge_requests_work_item_id_fkey', 'merge_requests', 'work_items', ['work_item_id'], ['id'])
    op.drop_table('merge_request_work_items')
    # ### end Alembic commands ###
