"""in progress label and item preferences

Revision ID: 3b51bb3f64a4
Revises: 0f4cfaea3b36
Create Date: 2026-09-25 12:31:01.565240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3b51bb3f64a4'
down_revision: Union[str, None] = '0f4cfaea3b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_item_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('work_item_id', sa.UUID(), nullable=False),
    sa.Column('watching', sa.Boolean(), nullable=False),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'work_item_id', name='uq_user_item_preference')
    )
    op.add_column('organizations', sa.Column('in_progress_label', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'in_progress_label')
    op.drop_table('user_item_preferences')
    # ### end Alembic commands ###
