"""init schema

Revision ID: 7338db7f9191
Revises: 
Create Date: 2026-09-25 02:32:53.951782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7338db7f9191'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gitlab_instance_url', sa.String(length=512), nullable=False),
    sa.Column('stale_threshold_days', sa.Integer(), nullable=False),
    sa.Column('stale_recheck_days', sa.Integer(), nullable=False),
    sa.Column('blocked_recheck_days', sa.Integer(), nullable=False),
    sa.Column('review_sla_days', sa.Integer(), nullable=False),
    sa.Column('overloaded_item_threshold', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('synced_projects',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('gitlab_project_id', sa.String(length=64), nullable=False),
    sa.Column('gitlab_full_path', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('web_url', sa.String(length=1024), nullable=False),
    sa.Column('uses_work_items_api', sa.Boolean(), nullable=False),
    sa.Column('gitlab_webhook_id', sa.String(length=64), nullable=True),
    sa.Column('webhook_secret_token', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reconciliation_backoff_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synced_projects_gitlab_project_id'), 'synced_projects', ['gitlab_project_id'], unique=True)
    op.create_table('users',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('gitlab_user_id', sa.String(length=64), nullable=False),
    sa.Column('gitlab_username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('encrypted_access_token', sa.String(length=2048), nullable=True),
    sa.Column('encrypted_refresh_token', sa.String(length=2048), nullable=True),
    sa.Column('token_expires_at', sa.String(length=64), nullable=True),
    sa.Column('in_tool_role', sa.Enum('ENGINEER', 'MANAGER', 'EXEC', 'ADMIN', name='in_tool_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_gitlab_user_id'), 'users', ['gitlab_user_id'], unique=True)
    op.create_table('check_ins',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('did_text', sa.String(length=4096), nullable=True),
    sa.Column('doing_text', sa.String(length=4096), nullable=True),
    sa.Column('blockers_text', sa.String(length=4096), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'check_in_date', name='uq_check_in_per_day')
    )
    op.create_table('labels',
    sa.Column('synced_project_id', sa.UUID(), nullable=False),
    sa.Column('gitlab_label_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('mapped_concept', sa.String(length=64), nullable=True),
    sa.Column('mapped_value', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['synced_project_id'], ['synced_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labels_gitlab_label_id'), 'labels', ['gitlab_label_id'], unique=True)
    op.create_table('milestones',
    sa.Column('synced_project_id', sa.UUID(), nullable=False),
    sa.Column('gitlab_milestone_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('starts_at', sa.Date(), nullable=True),
    sa.Column('due_at', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['synced_project_id'], ['synced_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_gitlab_milestone_id'), 'milestones', ['gitlab_milestone_id'], unique=True)
    op.create_table('notes',
    sa.Column('subject_user_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.String(length=8192), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_memberships',
    sa.Column('synced_project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_level', sa.Enum('GUEST', 'REPORTER', 'DEVELOPER', 'MAINTAINER', 'OWNER', name='gitlab_access_level'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['synced_project_id'], ['synced_projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('synced_project_id', 'user_id', name='uq_project_membership')
    )
    op.create_table('work_items',
    sa.Column('synced_project_id', sa.UUID(), nullable=False),
    sa.Column('gitlab_global_id', sa.String(length=128), nullable=False),
    sa.Column('gitlab_iid', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('item_type', sa.String(length=32), nullable=False),
    sa.Column('state', sa.Enum('OPENED', 'CLOSED', name='work_item_state'), nullable=False),
    sa.Column('web_url', sa.String(length=1024), nullable=False),
    sa.Column('assignee_user_id', sa.UUID(), nullable=True),
    sa.Column('author_user_id', sa.UUID(), nullable=True),
    sa.Column('milestone_id', sa.UUID(), nullable=True),
    sa.Column('gitlab_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gitlab_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.ForeignKeyConstraint(['synced_project_id'], ['synced_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_items_gitlab_global_id'), 'work_items', ['gitlab_global_id'], unique=True)
    op.create_table('blocked_flags',
    sa.Column('work_item_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=2048), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merge_requests',
    sa.Column('synced_project_id', sa.UUID(), nullable=False),
    sa.Column('work_item_id', sa.UUID(), nullable=True),
    sa.Column('gitlab_global_id', sa.String(length=128), nullable=False),
    sa.Column('gitlab_iid', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('state', sa.Enum('OPENED', 'CLOSED', 'MERGED', name='merge_request_state'), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('web_url', sa.String(length=1024), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=True),
    sa.Column('pipeline_status', sa.Enum('SUCCESS', 'FAILED', 'RUNNING', 'PENDING', 'CANCELED', 'SKIPPED', name='pipeline_status'), nullable=True),
    sa.Column('has_unresolved_threads', sa.Boolean(), nullable=False),
    sa.Column('approvals_required', sa.Integer(), nullable=True),
    sa.Column('approvals_received', sa.Integer(), nullable=False),
    sa.Column('gitlab_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gitlab_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['synced_project_id'], ['synced_projects.id'], ),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merge_requests_gitlab_global_id'), 'merge_requests', ['gitlab_global_id'], unique=True)
    op.create_table('work_item_labels',
    sa.Column('work_item_id', sa.UUID(), nullable=False),
    sa.Column('label_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ),
    sa.PrimaryKeyConstraint('work_item_id', 'label_id')
    )
    op.create_table('merge_request_reviewers',
    sa.Column('merge_request_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.Enum('REQUESTED', 'REVIEWED', 'APPROVED', name='review_state'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merge_request_id'], ['merge_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merge_request_id', 'user_id', name='uq_mr_reviewer')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merge_request_reviewers')
    op.drop_table('work_item_labels')
    op.drop_index(op.f('ix_merge_requests_gitlab_global_id'), table_name='merge_requests')
    op.drop_table('merge_requests')
    op.drop_table('blocked_flags')
    op.drop_index(op.f('ix_work_items_gitlab_global_id'), table_name='work_items')
    op.drop_table('work_items')
    op.drop_table('project_memberships')
    op.drop_table('notes')
    op.drop_index(op.f('ix_milestones_gitlab_milestone_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_labels_gitlab_label_id'), table_name='labels')
    op.drop_table('labels')
    op.drop_table('check_ins')
    op.drop_index(op.f('ix_users_gitlab_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_synced_projects_gitlab_project_id'), table_name='synced_projects')
    op.drop_table('synced_projects')
    op.drop_table('organizations')
    # ### end Alembic commands ###

    # Autogenerate doesn't emit DROP TYPE for Postgres enums — without these, a downgrade
    # followed by a re-upgrade fails with "type already exists".
    bind = op.get_bind()
    for enum_name in (
        "review_state",
        "pipeline_status",
        "merge_request_state",
        "work_item_state",
        "gitlab_access_level",
        "in_tool_role",
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
