"""standup follows

Revision ID: b5f64c4d5c6e
Revises: 3b51bb3f64a4
Create Date: 2026-09-25 12:44:01.942388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b5f64c4d5c6e'
down_revision: Union[str, None] = '3b51bb3f64a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standup_follows',
    sa.Column('manager_user_id', sa.UUID(), nullable=False),
    sa.Column('person_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['person_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manager_user_id', 'person_user_id', name='uq_standup_follow')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('standup_follows')
    # ### end Alembic commands ###
